### ISSUE TITLE
Attachments for daily notices

### ISSUE THREAD

**Issue by J-J-B-J** [J-J-B-J/get-sentral#15]
**Is your feature request related to a problem? Please describe.**
Yes. When there is an attachment for a daily notice, there is no way to view it.

**Describe the solution you'd like**
A new class should be created, called File. This class should have attributes such as the file type, URL and local URL (after downloading the file)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by SuperHarmony910** [comment]
How about we implement the feature without the local URL?

**Comment by J-J-B-J** [comment]
Hmm yes that could work. Thanks!
