### ISSUE TITLE
Daily reflection thingy majiggy

### ISSUE THREAD

**Issue by J-J-B-J** [J-J-B-J/get-sentral#18]
**Is your feature request related to a problem? Please describe.**
Nope. I would like to be able to view and edit the journal thingy beneath the timetable in Sentral. I don't know anybody who uses it but it would be fun to build.

**Describe the solution you'd like**
There should be an addition to the objects where you can fetch your journal entry for today, and another, seperate function to set the contents.

**Describe alternatives you've considered**
None.

**Additional context**
N/A

**Comment by J-J-B-J** [comment]
I'll get the progress bar working

**Comment by SuperHarmony910** [comment]
> I'll get the progress bar working

coolio- r u gonna merge #20 now?

**Comment by J-J-B-J** [comment]
Ok yeah and then I'll get the progress bar working
