### ISSUE TITLE
Fetch timetable from `portal/timetable/mytimetable/x/daily`

### ISSUE THREAD

**Issue by SuperHarmony910** [J-J-B-J/get-sentral#22]
**Is your feature request related to a problem? Please describe.**
Fetch the timetable from `portal/timetable/mytimetable/x/daily`. This way, we can fetch multiple days at once. 

**Describe the solution you'd like**
Completely revamp the timetable scraper code to scrape the timetable.

**Describe alternatives you've considered**

**Additional context**
In the HTML DOM structure, Sentral stores their periods horizontally; however, days are organised verticallym i.e. the first element in the DOM is Monday P1, the second element in the DOM is Tuesday P1. This makes me, as a programmer, very mildly infuriated.

**Comment by J-J-B-J** [comment]
Yes it is extremely annoying

**Comment by J-J-B-J** [comment]
@SuperHarmony910 do you want to scrape all days?

**Comment by J-J-B-J** [comment]
Update: @SuperHarmony910 says all days

**Comment by J-J-B-J** [comment]
To make the update backwards compatible with previous versions, the Sentral class will have the same attributes it used to, except:
- `Sentral().days` will be a new attribute that is a list of `SchoolDay` objects.
- `Sentral().classes` will be the classes for today, if not, tomorrow, if not, the day after tomorrow

**Comment by J-J-B-J** [comment]
Note: this update will not be backwards compatible.

**Comment by J-J-B-J** [comment]
The structure is just SOOOOOOOOOO ENRAGING!!! When there is more than one week shown at a time, instead of creating another `<table>`, it adds more `<tr>`s with a spacer. I cannot find an emoji to communicate how facepalm-ed I am.

**Comment by SuperHarmony910** [comment]
> The structure is just SOOOOOOOOOO ENRAGING!!! When there is more than one week shown at a time, instead of creating another `<table>`, it adds more `<tr>`s with a spacer. I cannot find an emoji to communicate how facepalm-ed I am.

NAHH WHATT💀💀

**Comment by J-J-B-J** [comment]
OH MY GOODNESS I JUST MADE THE `scrape_timetable()` FUNCTION FORTY-EIGHT LINES LONGER!!!
This is why:
### How to make a program scrape a terribly organised page of HTML:
1. Create a BeautifulSoup object based on the HTML
2. Find the `<table>` element
3. Split the table by weeks
4. Remove the spacer cells at the end of each week
5. If there are no weeks, return an empty list
6. Figure out the number of days in a week by finding all `<th>` cells with the class `timetable-date`, counting them and outputting that number divided by two
7. Repeat for each of the weeks:
8. Create a `Date` object for each of the second half of the `<th>` cells with the class `timetable-date`
9. Loop over the rows:
10. Set the row name to the cell on the left
11. Loop through all other cells:
12. If cell is inactive, add an `EmptyPeriod` object to the date object in the dictionary which is in the same column
13. If cell is active, add a `Period` object to the date object in the dictionary which is in the same column with all the date for it included
14. Compile the dictionary into `SchoolDay` objects
15. Return a list of `SchoolDay` objects

P.S. Don't feel bad for saying all days, @SuperHarmony910. The code would have been almost as complicated anyways.

**Comment by SuperHarmony910** [comment]
> OH MY GOODNESS I JUST MADE THE `scrape_timetable()` FUNCTION FORTY-EIGHT LINES LONGER!!! This is why:
> 
> ### How to make a program scrape a terribly organised page of HTML:
> 1. Create a BeautifulSoup object based on the HTML
> 2. Find the `<table>` element
> 3. Split the table by weeks
> 4. Remove the spacer cells at the end of each week
> 5. If there are no weeks, return an empty list
> 6. Figure out the number of days in a week by finding all `<th>` cells with the class `timetable-date`, counting them and outputting that number divided by two
> 7. Repeat for each of the weeks:
> 8. Create a `Date` object for each of the second half of the `<th>` cells with the class `timetable-date`
> 9. Loop over the rows:
> 10. Set the row name to the cell on the left
> 11. Loop through all other cells:
> 12. If cell is inactive, add an `EmptyPeriod` object to the date object in the dictionary which is in the same column
> 13. If cell is active, add a `Period` object to the date object in the dictionary which is in the same column with all the date for it included
> 14. Compile the dictionary into `SchoolDay` objects
> 15. Return a list of `SchoolDay` objects
> 
> P.S. Don't feel bad for saying all days, @SuperHarmony910. The code would have been almost as complicated anyways.

WTHHH THAT COMPLICATED-??
