### ISSUE TITLE
License

### ISSUE THREAD

**Issue by J-J-B-J** [J-J-B-J/get-sentral#27]
**Describe the bug**
The current licence (GNU General Public License v3.0) allows for commercial use, among other things that I don't really think are very good for an open-source project

**Expected behavior**
I think that:
- You must not commercialise the repo
- You must provide credit to the original authors
- You must share under the same licence

**Additional context**
The [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0) licence](https://creativecommons.org/licenses/by-nc-sa/4.0/) has all of these features. The text [here](https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode) can be copied into the `Licence` file, and the following code can be copied into `README.md`:

```html
<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.
```

The code outputs s logo and link like this:

<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.

@SuperHarmony910  what do you think?

**Comment by SuperHarmony910** [comment]
mmhm i definitely agree, cc by sa 4.0 definitely seems to meet a fairer policy.

**Comment by J-J-B-J** [comment]
ok
