### ISSUE TITLE
Journal disabling in app when journal is not available.

### ISSUE THREAD

**Issue by J-J-B-J** [J-J-B-J/get-sentral#35]
**Is your feature request related to a problem? Please describe.**
Yeah kinda. You can still edit the journal in the app even when it isn't on Sentral.

**Describe the solution you'd like**
When the journal is not available, the program should return a custom error such as `JournalNotAvailable`. Then, the app should have a try-except for this, as well as other example programs.

**Describe alternatives you've considered**
Setting the variable `SentralTimetable.JOURNAL_UNAVAILABLE`, then the app can check if the journal matches this text. But then what happens if the user enters that exact text?

**Additional context**
I recommend this is left until the three current pull requests are merged.

**Comment by SuperHarmony910** [comment]
yk what i'll just start this off bcs i'm bored
